config/routes.rb
Rails.application.routes.draw do
  get 'page/index'

  get 'page/designers'

  get 'page/about'

  get "product/:permalink", to: "products#show", as: "product"
  
  post "product/:permalink", to: "products#buy", as: "buy"
  post "product/:permalink", to: "products#buy"
  get "basket", to: "orders#show"
  mount Shoppe::Engine => "/shoppe"

  get 'products/index'

  root 'page#index'
  delete "basket", to: "orders#destroy"

  match "checkout", to: "orders#checkout", as: "checkout", via: [:get, :patch]
match "checkout/pay", to: "orders#payment", as: "checkout_payment", via: [:get, :post]
match "checkout/confirm", to: "orders#confirmation", as: "checkout_confirmation", via: [:get, :post]

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  private

  def current_order
    @current_order ||= begin
      if has_order?
        @current_order
      else
        order = Shoppe::Order.create(:ip_address => request.ip)
        session[:order_id] = order.id
        order
      end
    end
  end

  def has_order?
    !!(
      session[:order_id] &&
      @current_order = Shoppe::Order.includes(:order_items => :ordered_item).find_by_id(session[:order_id])
    )
  end

  helper_method :current_order, :has_order?
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
	def destroy
  		current_order.destroy
  		session[:order_id] = nil
  		redirect_to root_path, :notice => "Basket emptied successfully."
	end
	
	def checkout
    @order = Shoppe::Order.find(current_order.id)
    if request.patch?
      redirect_to checkout_payment_path
    end
  end
  def payment
    if request.post?
      redirect_to checkout_confirmation_path
    end
  end
  def confirmation
    if request.post?
      current_order.confirm!
      session[:order_id] = nil
      redirect_to root_path, :notice => "Order has been placed successfully!"
    end
  end


end

app/controllers/page_controller.rb
class PageController < ApplicationController
  def index
  	@products = Shoppe::Product.root.ordered.includes(:product_categories, :variants)
    @products = @products.group_by(&:product_category)
  end

  def designers
  end

  def about
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
	def index
    	@products = Shoppe::Product.root.ordered.includes(:product_categories, :variants)
    	@products = @products.group_by(&:product_category)
  	end

  	def show
    	@product = Shoppe::Product.root.find_by_permalink(params[:permalink])
  	end
  	def buy
  		@product = Shoppe::Product.root.find_by_permalink!(params[:permalink])
  		current_order.order_items.add_item(@product, 1)
  		redirect_to product_path(@product.permalink), :notice => "Product has been added successfuly!"
  	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/page_helper.rb
module PageHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Kanchh</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<div class="container-fluid">
	<nav class="navbar navbar-default">
	    <div class="container-fluid">
	      <!-- Brand and toggle get grouped for better mobile display -->
	      <div class="navbar-header">
		    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#defaultNavbar1">
		        <span class="sr-only">
		        	Toggle navigation
		        </span>
		        <span class="icon-bar">
		        	
		        </span>
		        <span class="icon-bar">
		        	
		        </span>
		        <span class="icon-bar">
		        	
		        </span>
	        </button>
	        <%= link_to 'Kanchh', root_path, :class => 'navbar-brand' %>
	        </div>
	      	
	      <div class="collapse navbar-collapse" id="defaultNavbar1">
	        <ul class="nav navbar-nav">
	          
	          <li class="dropdown">
	          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
	          	Men
	          	<span class="caret"></span>
	          </a>
	            <ul class="dropdown-menu" role="menu">
	              <li><a href="#">Polos & Tees</a></li>
	              <li><a href="#">Casual Shirts</a></li>
	              <li><a href="#">Jackets</a></li>
                  <li><a href="#">Ethnic Wear</a></li>
                </ul>
              </li>
	          <li class="dropdown"><a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Women<span class="caret"></span></a>
	            <ul class="dropdown-menu" role="menu">
	              <li><a href="#">Tops, Tees & Shirts</a></li>
	              <li><a href="#">Dresses</a></li>
	              <li><a href="#">Shorts and Skirts</a></li>
                  <li><a href="#">Ethnic Wear</a></li>
                </ul>
              </li>
            </ul>
	<ul class="nav navbar-nav navbar-right">
          <li><a href="#">Designers</a></li>
          <li><a href="#">Community</a></li>
          <li><a href="#">About</a></li>
          <li><a href="#">Sign In</a></li>
            </ul>
          </div>
	      <!-- /.navbar-collapse -->
        </div>
	    <!-- /.container-fluid -->
      </nav>
    
    	<% if has_order? && current_order %>
    	<div class="well well-lg">
			<p>
  				You have 
  				<%= pluralize current_order.total_items, 'item'%>
  				 in your basket which cost
  				<%= number_to_currency current_order.total_before_tax %>.
  			</p>
  			<%= link_to "View basket", basket_path, :style => 'float: right;', :class => 'btn btn-info' %>
  			<br>
  			<br>
  			<%= link_to "Checkout", checkout_path, :style => 'float: right;', :class => 'btn btn-success' %>
  			<br>
			<%= flash[:notice] %>
			</div>
		<% else %>
			
		<% end %>
	
     
	<div class="main">
		<%= yield %>
	</div>
     



	<footer class="footer-distributed">
	    <div class="footer-left">
	      <h3>Logo of<span>Kanchh</span></h3>
	      <p class="footer-company-name">Kanchh &copy; 2016</p>
        </div>
	    <div class="footer-center">
	      <div> <i class="fa fa-map-marker"></i>
	        <p><span>Irla</span> Mumbai, India</p>
          </div>
	      <div> <i class="fa fa-phone"></i>
	        <p>+91 123 345 4567</p>
          </div>
	      <div> <i class="fa fa-envelope"></i>
	        <p><a href="mailto:support@company.com">support@kanchh.com</a></p>
          </div>
        </div>
	    <div class="footer-right">
	      <p class="footer-company-about"> <span>About the company</span> Lorem ipsum dolor sit amet, consectateur adispicing elit. Fusce euismod convallis velit, eu auctor lacus vehicula sit amet. </p>
	      <div class="footer-icons"> <a href="#"><i class="fa fa-facebook"></i></a> <a href="#"><i class="fa fa-twitter"></i></a> <a href="#"><i class="fa fa-google-plus"></i></a> <a href="#"><i class="fa fa-instagram"></i></a> <a href="#"><i class="fa fa-pinterest"></i></a> </div>
        </div>
      </footer>

</div>


</body>
</html>

app/views/orders/_items.html.erb
<table width='100%' border='1'>
  <thead>
    <tr>
      <td>Quantity</td>
      <td>Product</td>
      <td>Sub-Total</td>
      <td>Tax</td>
      <td>Total</td>
    </tr>
  </thead>
  <tbody>
    <% order.order_items.each do |item| %>
    <tr>
      <td><%= item.quantity %></td>
      <td><%= item.ordered_item.full_name %></td>
      <td><%= number_to_currency item.sub_total %></td>
      <td><%= number_to_currency item.tax_amount %></td>
      <td><%= number_to_currency item.total %></td>
    </tr>
    <% end %>

    <% if order.delivery_service %>
    <tr>
      <td></td>
      <td><%= order.delivery_service.name %></td>
      <td><%= number_to_currency order.delivery_price %></td>
      <td><%= number_to_currency order.delivery_tax_amount %></td>
      <td><%= number_to_currency order.delivery_price + order.delivery_tax_amount %></td>
    </tr>
    <% end %>

  </tbody>
  <tfoot>
    <tr>
      <td colspan='4'>Sub-Total</td>
      <td><%= number_to_currency order.total_before_tax %></td>
    </tr>
    <tr>
      <td colspan='4'>Tax</td>
      <td><%= number_to_currency order.tax %></td>
    </tr>
    <tr>
      <td colspan='4'>Total</td>
      <td><%= number_to_currency order.total %></td>
    </tr>
  </tfoot>
</table>

app/views/orders/checkout.html.erb
<h2>Checkout</h2>
<%= render 'items', :order => @order %>




<%= form_for @order, :url => checkout_path do |f| %>
    <div>
        <div class="input-group input-group-lg">
            <span class="input-group-addon"><%= f.label :first_name, 'Name' %></span>
            <%= f.text_field :first_name, :class => 'form-control', :placeholder => 'First' %> 
            <%= f.text_field :last_name, :class => 'form-control', :placeholder => 'Last' %>
        </div>
        <div class="input-group input-group-lg">
            <span class="input-group-addon"><%= f.label :billing_address1, 'Address' %></span>
            <%= f.text_field :billing_address1, :class => 'form-control', :placeholder => 'Line 1' %> 
            <%= f.text_field :billing_address2, :class => 'form-control', :placeholder => 'Line 2' %>
            <%= f.text_field :billing_address3, :class => 'form-control', :placeholder => 'Line 3' %>
            <%= f.text_field :billing_address4, :class => 'form-control', :placeholder => 'Line 4' %>
        </div>
        <div class="input-group input-group-lg">
            <span class="input-group-addon"><%= f.label :billing_postcode, 'Post code' %></span>
            <%= f.text_field :billing_postcode, :class => 'form-control', :placeholder => 'ZIP Code' %> 
        </div>
        <div class="input-group input-group-lg">
            <span class="input-group-addon">Country</span>
            <%= f.collection_select :billing_country_id, Shoppe::Country.ordered, :id, :name, :class =>'form-control', :include_blank => true %>
            
        </div>
        <div class="input-group input-group-lg">
            <span class="input-group-addon">@</span>
            <%= f.text_field :email_address, :class => 'form-control', :placeholder => 'Email Address' %> 
        </div>
        <div class="input-group input-group-lg">
            <span class="input-group-addon"><%= f.label :phone_number %></span>
            <%= f.text_field :phone_number, :class => 'form-control', :placeholder => 'Email Address' %> 
        </div>
        <br>
        <%= f.submit 'Continue', :class => 'btn btn-primary' %>
    </div>

<% end %>

app/views/orders/confirmation.html.erb
<h2>Place your order</h2>
<%= render 'items', :order => current_order %>
<%= button_to "Place order", :class => 'btn btn-warning' %>

app/views/orders/payment.html.erb
<h2>Make your payment</h2>
<%= form_tag do %>
  <dl>
    <dt class="input-group-addon"><%= label_tag 'card_number' %></dt>
    <dd ><%= text_field_tag 'card_number' %></dd>
    <dt class="input-group-addon"><%= label_tag 'expiry' %></dt>
    <dd><%= text_field_tag 'expiry' %></dd>
    <dt class="input-group-addon"><%= label_tag 'security_code' %></dt>
    <dd><%= text_field_tag 'security_code' %></dd>
    <dd ><%= submit_tag "Continue", :class => 'btn btn-primary' %></dd>
  </dl>
<% end %>
<div>

app/views/orders/show.html.erb
<h2>Your basket</h2>
<%= render 'items', :order => current_order %>
<p><%= link_to 'Empty basket', basket_path, :method => :delete, :class => 'btn btn-danger' %></p>

app/views/page/about.html.erb
<h1>Page#about</h1>
<p>Find me in app/views/page/about.html.erb</p>

app/views/page/designers.html.erb
<h1>Page#designers</h1>
<p>Find me in app/views/page/designers.html.erb</p>

app/views/page/index.html.erb
<div id="carousel1" class="carousel slide" data-ride="carousel">
	<ol class="carousel-indicators">
	    <li data-target="#carousel1" data-slide-to="0" class="active"></li>
	    <li data-target="#carousel1" data-slide-to="1"></li>
	    <li data-target="#carousel1" data-slide-to="2"></li>
    </ol>
	<div class="carousel-inner" role="listbox">
	    <div class="item active">
	    	<%= image_tag '1.jpg', :class => 'center-block', :alt => 'First slide image' %>
	        <div class="carousel-caption">
	        	<h3>First slide Heading</h3>
	          	<p>First slide Caption</p>
            </div>
        </div>
	    <div class="item">
	    	
	    	<%= image_tag '2.jpg', :class => 'center-block', :alt => 'Second slide image' %>
	        <div class="carousel-caption">
	          	<h3>Second slide Heading</h3>
	          	<p>Second slide Caption</p>
            </div>
        </div>
	    <div class="item">
	    	<%= image_tag '3.jpg', :class => 'center-block', :alt => 'Third slide image' %>
	        <div class="carousel-caption">
	          <h3>Third slide Heading</h3>
	          <p>Third slide Caption</p>
            </div>
        </div>
    </div>
	<a class="left carousel-control" href="#carousel1" role="button" data-slide="prev">
		<span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span><span class="sr-only">Previous</span>
	</a>
	<a class="right carousel-control" href="#carousel1" role="button" data-slide="next">
		<span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span><span class="sr-only">Next</span>
	</a>
</div>

app/views/products/index.html.erb
<div class="jumbotron">
      <h1>Hello there :)</h1>
      <p>Hope you like the products you see. Enjoy shopping. </p>
      <p>
        
        <%= link_to 'Learn about us', :controller => 'page', :action => 'about', :class => 'btn btn-primary btn-lg', :role => 'button' %>
      </p>
</div>

<% @products.each do |category, products| %>
  <div class="row">
    <h3><%= category.name %></h3>
    <% products.each do |product| %>
      <div class="col-md-4">
        <div class="thumbnail">
          <%= image_tag product.default_image.path, :alt => 'Image of the product' %>
          <div class="caption">
            <h3><%= link_to product.name, product_path(product.permalink) %></h3>
            <p><%= product.short_description %></p>
            <p>
              <%= link_to number_to_currency(product.price), product_path(product.permalink), :class => 'btn btn-primary' %>
            </p>
          </div>
        </div>
      </div>
    <% end %>
  </div>
<% end %>

app/views/products/show.html.erb
<div class="jumbotron">
	<h1><%= @product.name %></h1>
	<p><%= @product.short_description %></p>
	<% if @product.default_image %>
  		<%= image_tag @product.default_image.path, :class => "img-responsive", :alt => "Placeholder image" %>
	<% end %>
	<p>
  		<b><%= number_to_currency @product.price %></b>
  		<%= link_to "Add to basket", product_path(@product.permalink), :method => :post, :class => 'btn btn-primary btn-lg', :role => 'button' %>
	</p>
	<hr>
		<%= simple_format @product.description %>
	<hr>
	<p>
		<%= link_to "Back to list", :controller => 'products', :action => 'index' , :class => 'btn btn-default btn-lg' %>
	</p>
</div>